steps:
- label: 'Deploy ios, android, and webgl (darwin)'
  command:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
    - export ANDROID_HOME=/Users/administrator/Android
    - export ANDROID_NDK_HOME=/Users/administrator/Android/ndk-bundle
    - export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
    - source ~/.bash_profile
    - ./build.sh -p ios,android,webgl -i -s release debug
    - cd out
    - tar -czvf filament-ios-darwin.tgz ios-debug ios-release
    - aws s3 cp filament-ios-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
    - tar -czvf filament-android-darwin.tgz android-debug android-release *.aar
    - aws s3 cp filament-android-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
    - tar -czvf filament-webgl-darwin.tgz cmake-webgl-debug/web cmake-webgl-release/web
    - aws s3 cp filament-webgl-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
  agents:
    queue: mac_ci_v5
  timeout_in_minutes: 90

- label: 'Deploy android and webgl (linux)'
  command:
    - ./build.sh -p android,webgl -i -s release debug
    - cd out
    - tar -czvf filament-android-linux.tgz android-debug android-release *.aar
    - aws s3 cp filament-android-linux.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
    - tar -czvf filament-webgl-linux.tgz cmake-webgl-debug/web cmake-webgl-release/web
    - aws s3 cp filament-webgl-linux.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
  agents:
    queue: android_ci_v5
  timeout_in_minutes: 90
