steps:
- label: 'Build ios, android, and webgl (darwin)'
  command:
    - source ~/.bash_profile
    - ./build.sh -p ios,android,webgl -i -s release debug
  agents:
    queue: mac_ci_v9
  timeout_in_minutes: 90

- label: 'Build android (linux)'
  command:
    - ./build.sh -p android,webgl -i -s release debug
  agents:
    queue: android_ci_v9
  timeout_in_minutes: 90
