steps:
- label: 'Deploy ios and darwin release builds'
  command:
    - source ~/.bash_profile
    - ./build.sh -c -p ios,desktop -i -s release
    - cd out

    - tar -czvf filament-ios-release-darwin.tgz ios-release
    - aws s3 cp filament-ios-release-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/

    - tar -czvf filament-darwin-release-darwin.tgz release
    - aws s3 cp filament-darwin-release-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/

  agents:
    queue: mac_ci_v9
  timeout_in_minutes: 90

- label: 'Deploy ios and darwin debug builds'
  command:
    - source ~/.bash_profile
    - ./build.sh -c -p ios,desktop -i -s debug
    - cd out

    - tar -czvf filament-ios-debug-darwin.tgz ios-debug
    - aws s3 cp filament-ios-debug-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/

    - tar -czvf filament-darwin-debug-darwin.tgz debug
    - aws s3 cp filament-darwin-debug-darwin.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/

  agents:
    queue: mac_ci_v9
  timeout_in_minutes: 90

- label: 'Deploy android release build'
  command:
    - ./build.sh -c -p android -i release
    - cd out

    - tar -czvf filament-android-release-linux.tgz android-release filament-android-release.aar
    - aws s3 cp filament-android-release-linux.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
  agents:
    queue: android_ci_v9
  timeout_in_minutes: 90

- label: 'Deploy android debug build'
  command:
    - ./build.sh -c -p android -i debug
    - cd out

    - tar -czvf filament-android-debug-linux.tgz android-debug filament-android-debug.aar
    - aws s3 cp filament-android-debug-linux.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
  agents:
    queue: android_ci_v9
  timeout_in_minutes: 90

- label: 'Deploy webgl release'
  command:
    - ./build.sh -c -p webgl -i release
    - cd out

    - tar -czvf filament-webgl-release-linux.tgz cmake-webgl-release/web
    - aws s3 cp filament-webgl-release-linux.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
  agents:
    queue: android_ci_v9
  timeout_in_minutes: 90

- label: 'Deploy webgl debug'
  command:
    - ./build.sh -c -p webgl -i debug
    - cd out

    - tar -czvf filament-webgl-debug-linux.tgz cmake-webgl-debug/web
    - aws s3 cp filament-webgl-debug-linux.tgz s3://ubiquity6-build/filament/$BUILDKITE_COMMIT/
  agents:
    queue: android_ci_v9
  timeout_in_minutes: 90
